
export const DELETE_TASK="DELETE_TASK";
export const UPDATE_TASK="UPDATE_TASK";
export const REQUEST_DATA="REQUEST_DATA";
export const RECEIVE_DATA="RECEIVE_DATA";

export const REQUEST_BOARD="REQUEST_BOARD";
export const RECEIVE_BOARD="RECEIVE_BOARD";

export const REQUEST_ADD_TASK="REQUEST_ADD_TASK";
export const RECEIVE_ADD_TASK="RECEIVE_ADD_TASK";
