
export const REQUEST_BOARD="REQUEST_BOARD";
export const RECEIVE_BOARD="RECEIVE_BOARD";

export const REQUEST_ADD_TASK="REQUEST_ADD_TASK";
export const RECEIVE_ADD_TASK="RECEIVE_ADD_TASK";

export const REQUEST_UPDATE_TASK="REQUEST_UPDATE_TASK";
export const RECEIVE_UPDATE_TASK="RECEIVE_UPDATE_TASK";

export const REQUEST_DELETE_TASK="REQUEST_DELETE_TASK";
export const RECEIVE_DELETE_TASK="RECEIVE_DELETE_TASK";
